services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      app-network:
        ipv4_address: 192.168.1.100
    environment:
      ENVIRONMENT: development
      MONGO_DB_URI: mongodb://root:example@192.168.1.101:27017/cert_shield_api
      MONGO_DB_NAME: cert_shield_api

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      app-network:
        ipv4_address: 192.168.1.101
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8787:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@192.168.1.101:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      app-network:
        ipv4_address: 192.168.1.102

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
