services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  
  mongo-express:
    image: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge