services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://db:27017/myapp
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge